#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)"

# sudo apt update
# sudo apt install llvm lld llvm-dev liblld-dev clang libclang-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev git
#
# wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz -O /tmp/zig.tar.xz
# tar -xvf /tmp/zig.tar.xz -C $HOME
# export PATH="$HOME/zig-linux-x86_64-0.14.0:$PATH"
#
# (
# cd $HOME
# git clone https://github.com/ghostty-org/ghostty.git
# git checkout v1.1.3
# )
#
# (
# cd $HOME/ghostty
# zig build -Doptimize=ReleaseFast
# cp -f $HOME/ghostty/zig-out/bin/ghostty $HOME/.local/bin
# mv $HOME/ghostty/zig-out/share/ghostty/themes $HOME/.config/ghostty
# )
