#!/usr/bin/env bash

set -e

LUA_VERSION=$(lua -v 2>&1 | grep -oE '[0-9]+\.[0-9]+' | head -n1)
TREE="$HOME/.local/share/nvim/rocks"
lang="$1"

luarocks \
    --lua-version=$LUA_VERSION \
    --tree=$TREE \
    install tree-sitter-$lang
